### ISSUE TITLE
HTTP-500 on String input in ausleihe-form

### ISSUE THREAD

**Issue by ironjan** [ironjan/klausurtool-ror#166]
**How does this problem happen?**

 1. go to http://ausleihe.fachschafts.website/internal/ausleihe
 2. Write a string like "foobar" into the form input
 3. Press weiter

**What does happen?**

HTTP-500 
```
Apr 12 16:17:08 fsmi-relentless docker[30626]: I, [2016-04-12T14:17:08.194334 #12]  INFO -- : Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.7ms)
Apr 12 16:17:08 fsmi-relentless docker[30626]: F, [2016-04-12T14:17:08.195500 #12] FATAL -- :
Apr 12 16:17:08 fsmi-relentless docker[30626]: NoMethodError (undefined method `old_lend_out' for nil:NilClass):
Apr 12 16:17:08 fsmi-relentless docker[30626]: app/controllers/ausleihe_controller.rb:44:in `block in switch'
Apr 12 16:17:08 fsmi-relentless docker[30626]: app/controllers/ausleihe_controller.rb:44:in `reject'
Apr 12 16:17:08 fsmi-relentless docker[30626]: app/controllers/ausleihe_controller.rb:44:in `switch'
```

**What do you expect to happen instead?**

"Folder not found for `foobar`"

**Comment by ironjan** [comment]
Fixed on latest master.
